feat: enforce VERSION requirement

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -46,4 +46,10 @@ jobs:
         id: verify_changed_files
         with:
           files: |
-             mix.exs
+             VERSION
+      - name: Fail Unless Versions Updated
+        id: fail_unless_changed
+        if: steps.verify_changed_files.outputs.any_changed == 'false'
+        run: |
+              echo "::error ::Please update the VERSION file"
+              exit 1
